
site_name: EVAPOTRAN Documentation
site_description: Documentation for the EVAPOTRAN Evapotranspiration Calculator
site_author: Flaha Agri Tech
copyright: '&copy; 2023 Flaha Agri Tech'

theme:
  name: material
  palette:
    primary: green
    accent: light green
  logo: img/Flaha_logo.svg
  favicon: img/Flaha_logo.png
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.highlight
    - content.tabs.link

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - attr_list
  - md_in_html
  - tables

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home: index.md
  - Getting Started:
    - Introduction: getting-started/introduction.md
    - Installation: getting-started/installation.md
    - Quick Start Guide: getting-started/quick-start.md
    - Key Concepts: getting-started/key-concepts.md
  - User Guide:
    - UI Overview: user-guide/ui-overview.md
    - Manual Calculator: user-guide/manual-calculator.md
    - EPW Import: user-guide/epw-import.md
    - Weather Visualization: user-guide/weather-visualization.md
    - Live Weather: user-guide/live-weather.md
    - Data Export: user-guide/data-export.md
    - Troubleshooting: user-guide/troubleshooting.md
  - Technical Reference:
    - Architecture: technical/architecture.md
    - Calculation Methods: technical/calculation-methods.md
    - Data Processing: technical/data-processing.md
    - Visualization: technical/visualization.md
    - Performance Optimization: technical/performance-optimization.md
    - Browser Compatibility: technical/browser-compatibility.md
  - API Documentation:
    - Core API: api/core-api.md
    - Weather Data API: api/weather-api.md
    - Visualization API: api/visualization-api.md
    - Utility Functions: api/utility-functions.md
    - Events: api/events.md
    - Integration Examples: api/integration-examples.md
  - Development:
    - Contributing: development/contributing.md
    - Code Guidelines: development/code-guidelines.md
    - Project Structure: development/project-structure.md
    - Build Process: development/build-process.md
    - Testing: development/testing.md
    - Release Process: development/release-process.md
    - Workflow: development/workflow.md
  - Deployment:
    - Overview: deployment/README.md
    - Local Deployment: deployment/local-deployment.md
    - Web Server: deployment/web-server.md
    - Production Checklist: deployment/production-checklist.md
    - Security: deployment/security.md
    - Performance: deployment/performance.md
    - Monitoring: deployment/monitoring.md
  - Case Studies:
    - Overview: case-studies/README.md
    - Vineyard Irrigation: case-studies/vineyard-irrigation.md
    - Greenhouse Management: case-studies/greenhouse-management.md
    - Urban Landscaping: case-studies/urban-landscaping.md
    - Drought Response: case-studies/drought-response.md
  - FAQ:
    - General: faq/general.md
    - Calculations: faq/calculations.md
    - Data: faq/data.md
    - Technical Issues: faq/technical-issues.md
  - Release Notes:
    - Version History: releases/version-history.md
    - Latest Release: releases/v0.2.0.md
    - Previous Releases: releases/previous-releases.md
    - Roadmap: releases/roadmap.md

plugins:
  - search
