
site_name: EVAPOTRAN Documentation
site_description: Documentation for the EVAPOTRAN Evapotranspiration Calculator
site_author: Flaha Agri Tech
copyright: '&copy; 2023 Flaha Agri Tech'

theme:
  name: material
  palette:
    primary: green
    accent: light green
  logo: img/Flaha_logo.svg
  favicon: img/Flaha_logo.png
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.highlight
    - content.tabs.link

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - attr_list
  - md_in_html
  - tables

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home: index.md
  - User Guide:
    - Getting Started: user-guide/getting-started.md
    - Installation: user-guide/installation.md
    - Manual Calculator: user-guide/manual-calculator.md
    - EPW Import: user-guide/epw-import.md
    - Weather Visualization: user-guide/weather-visualization.md
    - Live Weather: user-guide/live-weather.md
  - Technical Documentation:
    - Architecture: technical/architecture.md
    - Calculation Methods: technical/calculation-methods.md
    - Data Processing: technical/data-processing.md
    - Visualization: technical/visualization.md
    - Performance Optimization: technical/performance-optimization.md
  - Case Studies:
    - Overview: case-studies/index.md
    - Vineyard Irrigation: case-studies/vineyard-irrigation.md
    - Greenhouse Management: case-studies/greenhouse-management.md
    - Urban Landscape: case-studies/urban-landscape.md
    - Drought Response: case-studies/drought-response.md
  - Development:
    - Contributing: development/contributing.md
    - Code Guidelines: development/code-guidelines.md
    - Project Structure: development/project-structure.md
  - About:
    - License: about/license.md
    - Contact: about/contact.md

plugins:
  - search
