
site_name: EVAPOTRAN Documentation
site_description: Documentation for the EVAPOTRAN Evapotranspiration Calculator
site_author: Flaha Agri Tech
copyright: '&copy; 2023 Flaha Agri Tech'

theme:
  name: material
  palette:
    primary: green
    accent: light green
  logo: img/Flaha_logo.svg
  favicon: img/Flaha_logo.png
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.highlight
    - content.tabs.link

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - attr_list
  - md_in_html
  - tables

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Define the navigation structure
nav:
  - Home: index.md
  - Getting Started:
    - Introduction: getting-started/introduction.md
    - Installation: getting-started/installation.md
    - Quick Start: getting-started/quick-start.md
  - User Guide:
    - Overview: user-guide/overview.md
    - Manual Calculator: user-guide/manual-calculator.md
    - EPW Import: user-guide/epw-import.md
    - Weather Visualization: user-guide/weather-visualization.md
    - Live Weather: user-guide/live-weather.md
    - Troubleshooting: user-guide/troubleshooting.md
  - Technical:
    - Architecture: technical/architecture.md
    - Algorithms: technical/algorithms.md
    - Performance: technical/performance-optimization.md
    - API Reference: technical/api-reference.md
  - Development:
    - Contributing: development/contributing.md
    - Code Guidelines: development/code-guidelines.md
    - Project Structure: development/project-structure.md
  - Case Studies:
    - Vineyard Irrigation: case-studies/vineyard-irrigation.md
    - Greenhouse Management: case-studies/greenhouse-management.md
    - Urban Landscaping: case-studies/urban-landscaping.md
  - FAQ:
    - General: faq/general.md
    - Technical: faq/technical.md
  - About:
    - Contact: about/contact.md
    - License: about/license.md
    - Changelog: about/changelog.md

plugins:
  - search

extra:
  analytics:
    provider: google
    property: G-XXXXXXXXXX  # Replace with your Google Analytics tracking ID
  extra_css:
    - css/extra.css
