name: Deploy to DigitalOcean

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: |
          npm install
          cd EVAPOTRAN/server
          npm install
          
      - name: Build application
        run: npm run build
        
      - name: Deploy to DigitalOcean Droplet
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          script: |
            # Navigate to the application directory
            cd /var/www/flahacalc
            
            # Pull the latest changes
            git pull
            
            # Install dependencies (using npm install instead of npm ci)
            npm install
            cd EVAPOTRAN/server
            npm install
            
            # Build the application
            cd ../..
            npm run build
            
            # Restart the server
            pm2 restart flahacalc-server || pm2 start EVAPOTRAN/server/server.js --name flahacalc-server

