
name: Deploy to DigitalOcean

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: |
          npm install
          cd EVAPOTRAN/server
          npm install
          
      - name: Build application
        run: npm run build
        
      - name: Deploy to DigitalOcean
        uses: appleboy/ssh-action@master
        with:
          host: 207.154.202.6
          username: root
          key: ${{ secrets.DROPLET_SSH_KEY }}
          port: 22
          script: |
            # Check if the repository exists
            if [ ! -d "/var/www/flahacalc" ]; then
              echo "Creating application directory..."
              mkdir -p /var/www/flahacalc
              cd /var/www/flahacalc
              git clone https://github.com/rafatahmed/FlahaCalc.git .
            else
              # Update the repository with special handling for local changes
              cd /var/www/flahacalc
              bash scripts/server/handle-local-changes.sh || git pull
            fi
            
            # Install dependencies
            npm install
            cd EVAPOTRAN/server
            npm install
            cd ../..
            
            # Build application
            npm run build
            
            # Make all scripts executable
            find scripts -name "*.sh" -exec chmod +x {} \;
            
            # Update Nginx configuration
            echo "Updating Nginx configuration..."
            cp scripts/server/nginx/flahacalc.conf /etc/nginx/sites-available/flahacalc
            ln -sf /etc/nginx/sites-available/flahacalc /etc/nginx/sites-enabled/
            nginx -t && systemctl reload nginx
            
            # Restart server
            cd EVAPOTRAN/server
            pm2 restart flahacalc-server || pm2 start server.js --name flahacalc-server
            
            # Update HTML links for production
            cd /var/www/flahacalc
            bash scripts/deploy/update-links.sh
            
            # Run the fix-all script
            sudo bash scripts/server/fix-all.sh
            
            echo "Deployment completed successfully!"






