
name: Deploy to DigitalOcean

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: |
          npm install
          cd EVAPOTRAN/server
          npm install
          
      - name: Build application
        run: npm run build
        
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          
      - name: Deploy to DigitalOcean Droplet
        run: |
          doctl compute ssh ${{ secrets.DROPLET_NAME }} --ssh-command "cd /var/www/flahacalc && git pull && npm install && cd EVAPOTRAN/server && npm install && cd ../.. && npm run build && cd EVAPOTRAN/server && pm2 restart flahacalc-server || pm2 start server.js --name flahacalc-server"







