
name: Deploy to Production

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      apply_fixes:
        description: 'Apply fixes after deployment'
        required: false
        default: 'false'
        type: choice
        options:
          - 'true'
          - 'false'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: |
          npm install
          cd EVAPOTRAN/server
          npm install
          
      - name: Run linting and tests
        run: |
          npm run lint || echo "Linting issues found"
          npm test || echo "Tests not configured"
          
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: |
          npm install
          cd EVAPOTRAN/server
          npm install
          
      - name: Build application
        run: npm run build
        
      - name: Run pre-deployment checks
        run: bash scripts/deploy/pre-deploy-check.sh
        
      - name: Get changed files
        id: changed-files
        run: |
          echo "CHANGED_FILES=$(git diff --name-only HEAD~1 HEAD | tr '\n' ' ')" >> $GITHUB_ENV
          echo "Changed files: $(git diff --name-only HEAD~1 HEAD | tr '\n' ' ')"
        
      - name: Deploy to DigitalOcean
        uses: appleboy/ssh-action@master
        with:
          host: 207.154.202.6
          username: root
          key: ${{ secrets.DROPLET_SSH_KEY }}
          port: 22
          script: |
            # Run the safe deployment script
            bash /var/www/flahacalc/scripts/deploy/safe-deploy.sh
      
      - name: Verify deployment
        uses: appleboy/ssh-action@master
        with:
          host: 207.154.202.6
          username: root
          key: ${{ secrets.DROPLET_SSH_KEY }}
          port: 22
          script: |
            cd /var/www/flahacalc
            echo "Verifying API endpoint..."
            curl -s http://localhost:3000/test
            echo ""
            echo "Checking Node.js server status..."
            pm2 status flahacalc-server
            echo ""
            echo "Checking Nginx status..."
            systemctl status nginx | grep Active
            
      - name: Apply fixes if requested
        if: github.event.inputs.apply_fixes == 'true'
        uses: appleboy/ssh-action@master
        with:
          host: 207.154.202.6
          username: root
          key: ${{ secrets.DROPLET_SSH_KEY }}
          port: 22
          script: |
            cd /var/www/flahacalc
            bash scripts/server/fix-all.sh
            
  notify:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Send deployment notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: deployments
          SLACK_COLOR: ${{ job.status }}
          SLACK_TITLE: Deployment Complete
          SLACK_MESSAGE: 'FlahaCalc has been deployed to production. Commit message: ${{ github.event.head_commit.message }}'
          SLACK_FOOTER: 'Deployed by: ${{ github.actor }}'
        if: env.SLACK_WEBHOOK != ''
