# @format

name: Deploy to Production

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      apply_fixes:
        description: 'Apply fixes after deployment'
        required: false
        default: 'false'
        type: choice
        options:
          - 'true'
          - 'false'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: |
          npm install
          cd EVAPOTRAN/server
          npm install
          cd ../..
          
      - name: Build application
        run: npm run build
        
      - name: Deploy using pipeline approach
        uses: appleboy/ssh-action@master
        with:
          host: 207.154.202.6
          username: root
          key: ${{ secrets.DROPLET_SSH_KEY }}
          port: 22
          script: |
            # Run the safe deployment script
            cd /var/www/flahacalc
            
            # Make sure the script exists and is executable
            if [ ! -f "scripts/deploy/safe-deploy.sh" ]; then
              mkdir -p scripts/deploy
              
              # Copy the safe-deploy script from the repository
              curl -s https://raw.githubusercontent.com/rafatahmed/FlahaCalc/main/scripts/deploy/safe-deploy.sh > scripts/deploy/safe-deploy.sh
              chmod +x scripts/deploy/safe-deploy.sh
            fi
            
            # Run the safe deployment script
            bash scripts/deploy/safe-deploy.sh
            
      - name: Apply fixes if requested
        if: github.event.inputs.apply_fixes == 'true'
        uses: appleboy/ssh-action@master
        with:
          host: 207.154.202.6
          username: root
          key: ${{ secrets.DROPLET_SSH_KEY }}
          port: 22
          script: |
            cd /var/www/flahacalc
            bash scripts/server/fix-all.sh || echo "Fix script not found or failed"

  notify:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Send deployment notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: deployments
          SLACK_COLOR: ${{ job.status }}
          SLACK_TITLE: Deployment Complete
          SLACK_MESSAGE: "FlahaCalc has been deployed to production using the pipeline approach."
          SLACK_FOOTER: "Deployed by: ${{ github.actor }}"
        if: env.SLACK_WEBHOOK != ''
