name: Sync Documentation to Wiki

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
  workflow_dispatch:

jobs:
  sync-wiki:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
      
      - name: Sync documentation to wiki
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Clone wiki repository
          git clone https://x-access-token:${GH_TOKEN}@github.com/flaha-agritech/evapotran.wiki.git wiki-temp
          
          # Create Home page from index.md
          cp docs/index.md wiki-temp/Home.md
          
          # Copy documentation files to wiki
          find docs -name "*.md" -not -path "docs/index.md" | while read file; do
              # Get relative path without docs/ prefix and .md suffix
              rel_path=${file#docs/}
              rel_path=${rel_path%.md}
              
              # Replace directory separators with hyphens
              wiki_name=$(echo $rel_path | sed 's/\//-/g')
              
              # Copy the file with the new name
              cp "$file" "wiki-temp/$wiki_name.md"
              
              echo "Copied $file to $wiki_name.md"
          done
          
          # Fix links for wiki format
          cd wiki-temp
          find . -name "*.md" -exec sed -i 's/\.md)/)/g' {} \;
          find . -name "*.md" -exec sed -i 's/\.md#/#/g' {} \;
          find . -name "*.md" -exec sed -i 's/(\([^)]*\)\/\([^)]*\))/(\1-\2)/g' {} \;
          
          # Create sidebar navigation
          cat > _Sidebar.md << 'EOL'
          # Navigation
          
          - [Home](Home)
          - **Getting Started**
            - [Introduction](getting-started-introduction)
            - [Installation](getting-started-installation)
            - [Quick Start](getting-started-quick-start)
          - **User Guide**
            - [Overview](user-guide-overview)
            - [Manual Calculator](user-guide-manual-calculator)
            - [EPW Import](user-guide-epw-import)
            - [Weather Visualization](user-guide-weather-visualization)
            - [Live Weather](user-guide-live-weather)
          - **Technical Reference**
            - [Architecture](technical-architecture)
            - [Calculation Methods](technical-calculation-methods)
          - **Development**
            - [Contributing](development-contributing)
            - [Code Guidelines](development-code-guidelines)
            - [Project Structure](development-project-structure)
          - **FAQ**
            - [General](faq-general)
            - [Technical Issues](faq-technical-issues)
          - [Release Notes](releases-index)
          EOL
          
          # Create footer with link to main documentation
          cat > _Footer.md << 'EOL'
          ---
          For the full documentation with better navigation and search capabilities, visit our [documentation site](https://evapotran-doc.flaha.org).
          EOL
          
          # Commit and push changes
          git add .
          git commit -m "Update wiki documentation from GitHub Action"
          git push
          
          cd ..
          rm -rf wiki-temp